site_name: laoyutong的学习笔记
site_description: 前端 / AI / 工具链 笔记
repo_url: https://github.com/laoyutong/blog-content

docs_dir: docs

theme:
  name: material
  language: zh
  features:
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换浅色模式

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes

plugins:
  - search:
      lang: zh
